FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY . .
RUN go mod download && go mod tidy && CGO_ENABLED=0 go build -o /edge-agent ./cmd/edge-agent

FROM alpine:3.19
COPY --from=builder /edge-agent /edge-agent
CMD ["/edge-agent"]
